const app = require('./app')
const config = require('./utils/config')
const logger = require('./utils/logger')
require('./models/Project')
require('./models/Risks')
require('./models/Issues')
require('./models/Assumptions')
require('./models/Dependency')
app.listen(config.PORT, () => {
  logger.info(`Server running on port ${config.PORT}`)
})